### ISSUE TITLE
Load to packagist.org

### ISSUE THREAD

**Issue by andchir** [nlpcloud/nlpcloud-php#3]
Please load latest version to packagist.org.

**Comment by juliensalinas** [comment]
Thanks for raising this issue.
It was caused by a version mismatch between the `composer.json` version and the Github version.
This is now solved and the latest version is properly indexed by Packagist.
Is everything working as expected on your end?

**Comment by andchir** [comment]
@juliensalinas Thanks for the quick fix. Everything works correctly.
