### ISSUE TITLE
The "chatbot" method doesn't work.

### ISSUE THREAD

**Issue by andchir** [nlpcloud/nlpcloud-php#4]
Hello.

https://github.com/nlpcloud/nlpcloud-php/blob/master/src/NLPCloud.php#L54

I think in this line you need to replace "text" to "input".

**Comment by juliensalinas** [comment]
You're absolutely right. We just fixed it: https://github.com/nlpcloud/nlpcloud-php/commit/9e1f3ff9f0e0483b5ad1f0ae3e95c1067d715aaf
Sorry about that, and thanks a lot!
