### ISSUE TITLE
Unsupported operand types: string + string 

### ISSUE THREAD

**Issue by sunilkgrao** [nlpcloud/nlpcloud-php#5]
I get an Unsupported operand types: string + string error  in /workspace/vendor/nlpcloud/nlpcloud-client/src/NLPCloud.php:25

This is when the summarize api is called. This was working find till about 10 days ago. I did a composer install which seems to have broken it.

**Comment by juliensalinas** [comment]
Hello @sunilkgrao sorry about this error and thanks a lot for reporting it!
We just fixed it. Could you please download the latest version and let me know if it fixes your problem?
Looking forward to hearing from you.
